spring:
  application:
    name: inbyte-demo-admin
    alias: 易思后台系统demo
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /api

logging:
  level:
    com.inbyte.demo.web.dao: debug

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  page-size-zero: false
